### ISSUE TITLE
WIP: Development of Volcano Observatory Notice for Aviation (VONA) schema

### ISSUE THREAD

**Issue by mgoberfield** [wmo-im/iwxxm-modelling#23]
Ref: Issue [305](https://github.com/wmo-im/iwxxm/issues/305) in the wmo-im/iwxxm repository.

**Comment by mgoberfield** [comment]
VONA UML model completed, first iteration:
![image](https://user-images.githubusercontent.com/7852621/214374543-6c4e12ab-9d7d-48cd-b833-cf8f6174f9e8.png)

VONA XMI and schema, two real-world VONA examples in IWXXM XML form are included in the zip file.

Respectfully solicit reviews and comments from everyone (@blchoy, @amilan17, @dzinkhan, @jkorosi, @yg31, @moryakovdv)  on this first draft.

[VONA.zip](https://github.com/wmo-im/iwxxm-modelling/files/10492958/VONA.zip)

Best regards,

mark

**Comment by mgoberfield** [comment]
The VONA requirements were gleaned from the following documents:
 
[Handbook on the IAVW, Doc 9766.pdf](https://github.com/wmo-im/iwxxm-modelling/files/10493052/Handbook.on.the.IAVW.Doc.9766.pdf)

[METP5-VONA-TAC.pdf](https://github.com/wmo-im/iwxxm-modelling/files/10493055/METP5-VONA-TAC.pdf)

The TAC form was considered as the most basic, minimalist instance of the VONA.

**Comment by blchoy** [comment]
Just received the proposed Amendment 81 to ICAO Annex 3 for State consultation and this is the [TAC Template for VONA](https://github.com/wmo-im/iwxxm/files/10520336/Proposed_VONA_TAC_Template.pdf).  I don't see a difference from the TAC Template brought up in METP/5 posted in @mgoberfield 's post.

**Comment by blchoy** [comment]
Thanks @mgoberfield for his initial draft.  As the team has agreed to use WxObjects for new reports, we may want to take a more aggressive approach in refactoring items in the TAC template into element of WxObjects.  In particular, some elements in the TAC template like "Activity status" and "Duration" has multiple types of representation in a single element, while "Volcanic ash cloud height", "Height source" and "Movement" all have the same entry "NO VA CLD PRODUCED" which is unnecessary if these properties are contained in an object "VolcanicAshCloud", etc.

I have therefore simplified the model as below:

![Context Diagram Volcano Observatory Notice for Aviation](https://user-images.githubusercontent.com/30064374/215337305-10136f07-22b8-4f93-91da-3c9fa0b9306a.png)
![Context Diagram Phenomenon Property](https://user-images.githubusercontent.com/30064374/215337309-2a6374c7-0251-4fb3-84cf-9826d8939adf.png)

And a typical instance should look like (showing only significant items):

```
<iwxx:VONA>
    <gml:identifier/>
    <iwxxm:boundingPeriod/>
    <iwxxm:boundingVolume/>
    <iwxxm:phenomenonList xlink:href="http://codes.wmo.int/49-2/MeteorologicalFeature/VOLCANO"/>
    <iwxxm:issueTime/>
    <iwxxm:originatingCentre/>
    <iwxxm:phenomenonCatetory/>
    <iwxxm:phenomenonTime/>    <- Item 3: Time of origin
    <iwxxm:feature>
        <iwxxm:MeteorologicalFeature>
            <gml:identifier/>
            <iwxxm:phenomenon xlink:href="http://codes.wmo.int/49-2/MeteorologicalFeature/VOLCANO"/>
            <iwxxm:phenomeonGeometry/>    <- Item 5: Location of volcano or volcanic ash source (and volcanic ash too?)
            <iwxxm:phenomenonProperty>
                <iwxxm:VolcanoProperty>
                    <iwxxm:name/>    <- Item 4: Name of volcano (Part 1)
                    <iwxxm:IAVCEINumber/>    <- Item 4: Name of volcano (Part 2)
                    <iwxxm:sourceElevation/>    <- Item 7: Source elevation
                </iwxxm:VolcanoProperty>
            </iwxxm:phenomenonProperty>
            <iwxxm:phenomenonProperty>
                <iwxxm:VolcanicActivty>
                    <iwxxm:activityStatus/>    <- Item 12: Activity status
                    <iwxxm:lastVolcanicAshEmissionTime/>    <- Item 12: Activity status (as necessary)
                    <iwxxm:resuspendedVolcanicAsh/>    <- Item 12: Activity status (as necessary)
                    <iwxxm:onsetTime/>    <- Item 13: Onset time
                    <iwxxm:duration/>    <- Item 14: Duration
                </iwxxm:VolcanicActivity>
            </iwxxm:phenomenonProperty>
            <iwxxm:phenomenonProperty>
                <iwxxm:VolcanicAshCloud>
                    <iwxxm:height/>    <- Item 15: Volcanic ash cloud height
                    <iwxxm:heightSource/>    <- Item 16: Height source
                    <iwxxm:movement/>    <- Item 17: Movement
                </iwxxm:VolcanicAshCloud>
            </iwxxm:phenomenonProperty>
        </iwxxm:MeteorologicalFeature>
    </iwxxm:feature>
    <iwxxm:noticeNumber/>    <- Item 8: Notice number
    <iwxxm:currentColourCode/>    <- Item 9: Current colour code
    <iwxxm:previousColourCode/>    <- Item 10: Prevous colour code
    <iwxxm:nameOfSVO/>    <- Item 11: Name SVO
    <iwxxm:contact/>    <- Item 18: Contacts
    <iwxxm:remark/>    <- Item 19: Remarks
    <iwxxm:nextNotice/>    <- Item 20: Next Notice
</iwxxm:VONA>
```

I have to say that a discussion with ICAO METP WG-MOG is required to clarify some inferred concepts (like the mentioning of LAST VA EMISSION nnnnnnnn/nnnnZ means there is no volcanic activity at the time being?), possibility of further re-factoring (separation of temporal and textual description of Item 14: Duration), do we want to be more specific on what is being referred to (volcano, vent or ash cloud?) by the location in Item 5, and more verbose description of terms like "ONGOING EPISODIC" to be included in the notes part of the schema.

Let's discuss at the team's meeting today (30 Jan 2023).

**Comment by blchoy** [comment]
One more option for consideration:

```
<iwxx:VONA>
    ...
    <iwxxm:feature>
        <iwxxm:MeteorologicalFeature>
            ...
            <iwxxm:phenomeonGeometry/>    <- This geometric description is now solely for the volcano itself
            <iwxxm:phenomenonProperty>
                <iwxxm:VolcanoProperty/>
            </iwxxm:phenomenonProperty>
            <iwxxm:phenomenonProperty>
                <iwxxm:VolcanicActivty/>
            </iwxxm:phenomenonProperty>
        </iwxxm:MeteorologicalFeature>
    </iwxxm:feature>
    <iwxxm:feature>
        <iwxxm:MeteorologicalFeature>
            ...
            <iwxxm:phenomeonGeometry/>    <- This geometric description is now solely for the volcanic ash cloud
            <iwxxm:phenomenonProperty>
                <iwxxm:VolcanicAshCloud/>
            </iwxxm:phenomenonProperty>
        </iwxxm:MeteorologicalFeature>
    </iwxxm:feature>
    <iwxxm:feature>     <- If there is more than one volcanic ash cloud one can add a second feature for description
        <iwxxm:MeteorologicalFeature>
            ...
            <iwxxm:phenomeonGeometry/>   
            <iwxxm:phenomenonProperty>
                <iwxxm:VolcanicAshCloud/>
            </iwxxm:phenomenonProperty>
        </iwxxm:MeteorologicalFeature>
    </iwxxm:feature>
    <iwxxm:noticeNumber/>
    <iwxxm:currentColourCode/>
    <iwxxm:previousColourCode/>
    <iwxxm:nameOfSVO/>
    <iwxxm:contact/>
    <iwxxm:remark/>
    <iwxxm:nextNotice/>
</iwxxm:VONA>
```
